syntax = "proto3";

package game;

message Empty {}

message ClientMessage {
	oneof message {
		bytes gdata = 1;
		Login login = 2;
		CreateAccount createAccount = 3;
		StartGame startGame = 4;
		bool allowBotsOrder = 5;
		QuitWaitingRoom quitWaitingRoom = 6;
		Empty askTimeDelta = 7;
	}
}


message Login {
	string pseudo = 1;
	string password = 2;
}

message CreateAccount {
	string pseudo = 1;
	string password = 2;
}

message StartGame {
	string gamemode = 1;
	bytes data = 2;
}

message QuitWaitingRoom {
		
}

message JoinRoom {
	string room = 1;
}




message ServerMessage {
	oneof message {
		bytes gdata = 1;
		SuccessResult createAccountResult = 2;
		SuccessResult loginResult = 3;
		Error error = 4;
		WaitingInfo waitingInfo = 5;
		double timeDeltaDate = 6;
		StartGameServer startGame = 7;
	}
}

message StartGameServer {
	int32 playerIdx = 1;
	int32 total = 2;
	string gamemode = 3;
	bytes startData = 4;
	bytes gdata = 5;
}

message Error {
	string message = 1;
	int32 code = 2;
}

message SuccessResult {
	bool success = 1;
}

message WaitingUser {
	optional string pseudo = 1;
	bool allowBots = 2;
	bool isBot = 3;
}

message WaitingInfo {
	int32 total = 1;
	string room = 2;
	repeated WaitingUser users = 3;
}


