syntax = "proto3";

package game_turrets;

message Empty {}

message Player {
	float x = 1;
	float y = 2;
	float vx = 3;
	float vy = 4;
	float dirX = 5;
	float dirY = 6;
	float alive = 7;
	int32 score = 8;
	float attackMunitions = 9;
}

message Bullet {
	float x = 1;
	float y = 2;
	float vx = 3;
	float vy = 4;
	float ax = 5;
	float ay = 6;
	float maxDist = 7;
	bool isRed = 8;
	float traveledDist = 9;
}

message Turret {
	bool taken = 1;
	bool redTeam = 2;
}

message State {
	repeated Player players = 1;
	repeated Turret turrets = 2;
	float time = 3;
	repeated Bullet bullets = 4;
}

message Throw {
	float x = 1;
	float y = 2;
}

message QInput {
	double timestamp = 1;
	oneof action {
		float dirX = 2;
		float dirY = 3;

		// Aiming / throwing
		Throw throwTarget = 4;
		Throw throwDir = 5;
		Empty throwAuto = 6;
		Empty throwOff = 7;
	}
}

message Input {
	QInput data = 1;
	float player = 2;
}

message ServerMessage {
	double timestamp = 1;
	bytes state = 2;
	repeated Input inputs = 3;
}

message ClientMessage {
	double timestamp = 1;
	repeated QInput inputs = 2;
}

message StartData {
	int32 skin = 1;
	int32 preferTeam = 2;
}

message StartPlayerInfo {
	float x = 1;
	float y = 2;
	bool isRed = 3;
}

message StartDataClient {
	repeated StartPlayerInfo players = 1;
}
